spring:
  datasource:
    url: jdbc:mysql://mysql-db:3306/todolist
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        boot:
          allow_jdbc_metadata_access: false
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

jwt:
  secret: yoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkeyyoursecretkey
  expirationMs: 86400000
