apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod
  # 선택(select) 할때 labels 필요 
  labels:
    app: my-first-pod
# 이미지 가져올때     
spec:  
  containers:
  - name: my-first-pod
    image: captainyun/k8s-todo-front-app:v1


# apiVersion: v1
# kind: Pod 
# metadata: 
#   name: my-first-pod2
#   labels:
#     app: my-first-pod2
#   spec:
#     containers:
#     - name: my-first-pod2
#       image: hhiipp/k8s-todo-front-app:v1
