apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql  # WordPress에서 이 이름으로 MySQL에 연결
spec:
  ports:
    - port: 3306  # MySQL 기본 포트
  selector:
    app: mysql  # MySQL 파드와 연결하기 위한 selector
  type: NodePort  # 내부 서비스 연결용
---
# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"   # MySQL root 비밀번호
        - name: MYSQL_DATABASE
          value: "wordpress"  # WordPress 데이터베이스 이름
        - name: MYSQL_USER
          value: "wordpressuser"  # WordPress 데이터베이스 사용자 이름
        - name: MYSQL_PASSWORD
          value: "1234"  # WordPress 데이터베이스 사용자 비밀번호
        ports:
        - containerPort: 3306
