apiVersion: v1
kind: Service
metadata:
  name: my-first-service
spec:
  selector:
    app: my-first-pod
  ports:
  - name: http
    port: 80
    targetPort: 5173
    nodePort: 30080
  type: LoadBalancer