apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"   # MySQL root 비밀번호
        - name: MYSQL_DATABASE
          value: "todolist"  #  데이터베이스 이름
        - name: MYSQL_USER
          value: "todolistuser"  #  데이터베이스 사용자 이름
        - name: MYSQL_PASSWORD
          value: "1234"  #  데이터베이스 사용자 비밀번호
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-storage 
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: mysql
