apiVersion: v1
kind: PersistentVolume
metadata:  # 여기 matadata를 metadata로 수정
  name: mysql-pv
spec:  # 여기 spac를 spec으로 수정
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/data/mysql
