apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: mysql-pvc
spec: 
  volumeName: mysql-pv
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: standard  # 이 줄을 추가