apiVersion: v1
kind: Service
metadata:
  name: wordpress-service  # WordPress에 접근할 외부 서비스
spec:
  ports:
    - port: 80  # HTTP 기본 포트
  selector:
    app: wordpress  # WordPress 파드와 연결하기 위한 selector
  type: NodePort  # 외부 접속을 허용
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend  # 이 부분을 추가
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:6.2.1-apache
        name: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_DB_USER
          value: wordpressuser
        - name: WORDPRESS_DB_PASSWORD
          value: "1234"
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes: 
      - name : wordpress-storage
        persistentVolumeClaim:
          claimName: mysql-pvc