apiVersion: v1
kind: Service
metadata:
  name: my-test-service
spec:
  selector:
    app: my-test-pod
  ports:
  - name: http
    port: 5173
    targetPort: 5173
    nodePort: 30081
  type: NodePort

