version: '3.8'
services:
  my-mysql-db:
    image: mysql:8.0.39
    environment:
      - MYSQL_ROOT_PASSWORD=mymysql
      - MYSQL_DATABASE=mycompany
    ports: 
      - 3307:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-net

  my-springboot-app:
    build: 
      context: ./spring-app
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      - my-net
    depends_on:
      - my-mysql-db
    environment:
      - spring_datasource_url=jdbc:mysql://my-mysql-db:3306/mycompany?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - spring_datasource_username=root
      - spring_datasource_password=mymysql
  #   # restart: always

  my-react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - my-net
    # depends_on:
    #   - my-mysql-db
    volumes:
      - ./react-app/build:/usr/share/nginx/html




networks: 
  my-net:

volumes:
  mysql-data: